/**
 * Lightweight proxy meshes for the editing viewport. These are NOT the printable
 * geometry (that is generated by OpenSCAD at preview/export, see
 * docs/ARCHITECTURE.md). A proxy is a cheap skeletal stand-in built from the
 * module's domain ports: a hub at the module origin, a tube arm out to each
 * port, and a colored marker at each port mouth (male vs female).
 */

import * as THREE from 'three'
import { getTranslation, portsOf, type Mat4, type Module } from '../domain'

const BODY_COLOR = 0x9aa0a6
const BODY_SELECTED = 0xfb815e
const MALE_COLOR = 0xfb815e
const FEMALE_COLOR = 0x33373e

const UP_Y = new THREE.Vector3(0, 1, 0)

export interface ModuleObject {
  group: THREE.Group
  setSelected(on: boolean): void
  dispose(): void
}

export function buildModuleObject(module: Module): ModuleObject {
  const group = new THREE.Group()
  group.userData.moduleId = module.id

  const bodyMat = new THREE.MeshStandardMaterial({
    color: BODY_COLOR,
    roughness: 0.65,
    metalness: 0,
  })
  const disposables: { dispose(): void }[] = [bodyMat]

  const ports = portsOf(module)
  const hubRadius = Math.max(...ports.map((p) => p.section.nominalSize / 2), 8)

  for (const p of ports) {
    const pos = getTranslation(p.transform)
    const target = new THREE.Vector3(pos[0], pos[1], pos[2])
    const radius = p.section.nominalSize / 2 + 1
    const len = target.length()

    if (len > 1e-3) {
      const geo = new THREE.CylinderGeometry(radius, radius, len, 20, 1, true)
      const arm = new THREE.Mesh(geo, bodyMat)
      arm.position.copy(target.clone().multiplyScalar(0.5))
      arm.quaternion.setFromUnitVectors(UP_Y, target.clone().normalize())
      group.add(arm)
      disposables.push(geo)
    }

    const markerGeo = new THREE.SphereGeometry(radius * 0.95, 16, 12)
    const markerMat = new THREE.MeshStandardMaterial({
      color: p.gender === 'male' ? MALE_COLOR : FEMALE_COLOR,
      roughness: 0.5,
    })
    const marker = new THREE.Mesh(markerGeo, markerMat)
    marker.position.copy(target)
    group.add(marker)
    disposables.push(markerGeo, markerMat)
  }

  const hubGeo = new THREE.SphereGeometry(hubRadius, 20, 16)
  group.add(new THREE.Mesh(hubGeo, bodyMat))
  disposables.push(hubGeo)

  applyTransform(group, module.transform)

  return {
    group,
    setSelected(on: boolean) {
      bodyMat.color.setHex(on ? BODY_SELECTED : BODY_COLOR)
    },
    dispose() {
      for (const d of disposables) d.dispose()
    },
  }
}

/** Write a domain Mat4 onto an Object3D (decomposed so the gizmo can drive it). */
export function applyTransform(obj: THREE.Object3D, m: Mat4): void {
  new THREE.Matrix4()
    .fromArray(m as unknown as number[])
    .decompose(obj.position, obj.quaternion, obj.scale)
}

/** Read an Object3D's current transform back as a domain Mat4. */
export function readTransform(obj: THREE.Object3D): Mat4 {
  obj.updateMatrix()
  return [...obj.matrix.elements] as unknown as Mat4
}
